---

- name: Install Shairport Packages
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - build-essential
    - git
    - xmltoman
    - autoconf
    - automake
    - libtool
    - libdaemon-dev
    - libasound2-dev
    - libpopt-dev
    - libconfig-dev
    - avahi-daemon
    - libavahi-client-dev
    - libssl-dev

- name: Create Shairport Group
  group:
    name: shairport-sync
    system: yes
    state: present

- name: Add Shairport User
  user:
    name: shairport-sync
    group: shairport-sync
    groups: audio,shairport-sync
    system: yes
    createhome: no
    shell: /usr/bin/nologin

- name: Download Shairport-sync to /opt
  git:
    repo: 'https://github.com/mikebrady/shairport-sync.git'
    dest: /opt/shairport-sync

- name: Run Autoreconf tool
  shell: "autoreconf -i -f"
  args:
    chdir: /opt/shairport-sync

- name: Run Configure tool
  shell: "./configure --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-systemd"
  args:
    chdir: /opt/shairport-sync

- name: Build Shairport-sync from Source
  make:
    chdir: /opt/shairport-sync

- name: Install Shairport-sync
  make:
    target: install
    chdir: /opt/shairport-sync

- name: Enable Shairport-sync Service
  systemd:
    name: shairport-sync
    enabled: yes
    state: started

## TODO: edit service for start playback script
