---

- name: Create app Group
  group:
    name: app
    system: yes
    state: present

- name: Add app User
  user:
    name: app
    group: app
    system: yes
    createhome: no
    shell: /usr/bin/nologin

- name: Update apt to include Nodejs sources
  shell: "curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -"

- name: Install nodejs
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - nodejs

- name: Download Bass-OS Repositorys
  git:
    repo: 'https://github.com/Julius112/{{ item }}.git'
    dest: /opt/{{ item }}
    force: yes
    version: devel
  with_items:
    - bassOS-service
    - bassOS-UI

- name: Install the Bass-OS dependencies
  npm:
    path: /opt/{{ item }}
  with_items:
    - bassOS-service
    - bassOS-UI

- name: Allow Bass-OS user to sudo #TODO security risk
  copy:
    src: files/011_app-nopasswd
    dest: /etc/sudoers.d/011_app-nopasswd
    mode: 0440

- name: Install the Bass-OS Services
  copy:
    src: files/{{ item }}.service
    dest: /lib/systemd/system/{{ item }}.service
    mode: 0644
  with_items:
    - bass-os-service
    - bass-os-ui

- name: Enable Bass-OS Services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
    daemon-reload: yes
  with_items:
    - bass-os-service
    - bass-os-ui
