---

#- name: Create app Group
#  group:
#    name: app
#    system: yes
#    state: present
#
#- name: Add app User
#  user:
#    name: app
#    group: app
#    system: yes
#    createhome: no
#    shell: /usr/bin/nologin
#
#- name: Install npm
#  apt: name={{item}} state=latest update_cache=yes
#  with_items:
#    - npm
#
#- name: Install required npm packages
#  shell: "npm install {{ item }}"
#  with_items:
#    - "express"
#    - "body-parser"

- name: Download Bass-OS Repository
  git:
    repo: 'https://github.com/Julius112/bOS10.git'
    dest: /opt/bOS10
    force: yes

- name: Install the Bass-OS Service
  copy:
    src: /opt/bOS10/code/bass-os.service
    dest: /lib/systemd/system/bass-os.service
    mode: 0644
    remote_src: yes

- name: Enable Bass-OS Service
  systemd:
    name: bass-os
    enabled: yes
    state: started
