---

- name: Set Default Output to USB Soundcard
  lineinfile:
    dest: /usr/share/alsa/alsa.conf
    regexp: '^defaults.ctl.card'
    line: 'defaults.ctl.card 1'
  notify: Reload ALSA

- name: Set Default PCM to USB Soundcard
  lineinfile:
    dest: /usr/share/alsa/alsa.conf
    regexp: '^defaults.pcm.card'
    line: 'defaults.pcm.card 1'
  notify: Reload ALSA

- name: Set the pretty hostname to BassOS
  copy:
    src: files/machine-info
    dest: /etc/machine-info
    mode: 0644

- name: Enable Automount of USB devices
  copy:
  args:
    src: files/11-media-by-label-auto-mount.rules
    dest: /etc/udev/rules.d/11-media-by-label-auto-mount.rules
    mode: 0644

#TODO: add tasks https://www.howtogeek.com/167195/how-to-change-your-raspberry-pi-or-other-linux-devices-hostname/
