---
- hosts: raspberry
  become: yes
  tasks:

    - include: tasks/system.yml
    - meta: flush_handlers

    - include: tasks/bluetooth.yml

    - include: tasks/airplay.yml

    - include: tasks/mpd.yml

    - include: tasks/app.yml

  handlers:
    - name: Reload ALSA
      shell: alsactl kill rescan
